"""add liked_travel_package tb

Revision ID: 1826cbf4483d
Revises: c99a58354097
Create Date: 2024-02-12 12:01:34.644536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1826cbf4483d'
down_revision = 'c99a58354097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liked_travel_packages',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('travel_package_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['travel_package_id'], ['travel_package.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'travel_package_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liked_travel_packages')
    # ### end Alembic commands ###
