"""reinstate travel package tables

Revision ID: 3164a9c33ea8
Revises: 45dab29ae162
Create Date: 2024-02-08 14:20:38.462948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3164a9c33ea8'
down_revision = '45dab29ae162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('hotel', sa.String(length=100), nullable=True),
    sa.Column('hotel_description', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('package_price', sa.Float(), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=False),
    sa.Column('longitude', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travel_package_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('travel_package_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['travel_package_id'], ['travel_package.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travel_package_image')
    op.drop_table('travel_package')
    # ### end Alembic commands ###
