"""update models.py for user image

Revision ID: 89eb4d278caa
Revises: c134bafb1ad5
Create Date: 2024-02-23 12:42:03.609311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89eb4d278caa'
down_revision = 'c134bafb1ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_image')
    # ### end Alembic commands ###
