"""Added latitude and longitude fields to TravelPackage model

Revision ID: 93acde3c0db3
Revises: ed8afed26715
Create Date: 2024-02-07 13:25:12.275198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93acde3c0db3'
down_revision = 'ed8afed26715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.String(length=50), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    with op.batch_alter_table('travel_package_image', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_package_image', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('travel_package', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
