"""update destination table

Revision ID: c134bafb1ad5
Revises: 1826cbf4483d
Create Date: 2024-02-21 13:00:19.606331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c134bafb1ad5'
down_revision = '1826cbf4483d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('liked_travel_packages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liked_travel_packages',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('travel_package_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['travel_package_id'], ['travel_package.id'], name='liked_travel_packages_travel_package_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='liked_travel_packages_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'travel_package_id', name='liked_travel_packages_pkey')
    )
    op.drop_table('destination')
    # ### end Alembic commands ###
