"""Create TravelPackage and TravelPackageImage tables

Revision ID: c5f2db1f54b5
Revises: 24b414363f4b
Create Date: 2024-02-08 11:57:48.372043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f2db1f54b5'
down_revision = '24b414363f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('hotel', sa.String(length=100), nullable=True),
    sa.Column('hotel_description', sa.Text(), nullable=True),
    sa.Column('icons', sa.String(length=100), nullable=True),
    sa.Column('package_price', sa.Float(), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=False),
    sa.Column('longitude', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travel_package_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('travel_package_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['travel_package_id'], ['travel_package.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travel_package_image')
    op.drop_table('travel_package')
    # ### end Alembic commands ###
