"""Add duration filed

Revision ID: d3da56bdc47a
Revises: c5f2db1f54b5
Create Date: 2024-02-08 12:11:23.290174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3da56bdc47a'
down_revision = 'c5f2db1f54b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_package', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
