"""add new class for wished holiday

Revision ID: f83ef7dd43bc
Revises: 3164a9c33ea8
Create Date: 2024-02-10 14:09:11.619647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83ef7dd43bc'
down_revision = '3164a9c33ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wished_holiday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holiday_type', sa.String(length=50), nullable=False),
    sa.Column('travel_duration', sa.Integer(), nullable=False),
    sa.Column('price_range', sa.String(length=50), nullable=False),
    sa.Column('travel_time', sa.String(length=100), nullable=False),
    sa.Column('departure_location', sa.String(length=100), nullable=False),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wished_holiday')
    # ### end Alembic commands ###
